#ifndef INPUT_ACTION_H
#define INPUT_ACTION_H

enum InputAction {
    ACTION_NONE = 0,

    ACTION_NEXT_SCREEN,
    ACTION_PREV_SCREEN,

    ACTION_MUSIC_NEXT,
    ACTION_MUSIC_PREV,
    ACTION_MUSIC_PLAY_PAUSE,

    ACTION_GAME_JUMP,
    ACTION_GAME_EXIT,

    ACTION_OTA_MODE,

    ACTION_MENU_ENTER,
    ACTION_MENU_NEXT,
    ACTION_MENU_SELECT,
    ACTION_MENU_BACK,
    ACTION_CLOCK_STYLE_NEXT,
    ACTION_TRIP_RESET
};

#endif
